# Generated by Django 2.2.4 on 2019-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('off', models.DecimalField(decimal_places=1, max_digits=100)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
