# Generated by Django 2.2.4 on 2019-09-17 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20190917_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2019, 9, 17, 15, 17, 29, 735228)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='off',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=100),
        ),
    ]
