# Generated by Django 2.2.4 on 2019-09-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20190917_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 15, 20, 47, 68817)),
        ),
    ]
