# Generated by Django 2.2.4 on 2019-09-18 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20190917_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
