# Generated by Django 2.2.4 on 2019-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20190920_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=25, unique=True),
        ),
    ]
