# Generated by Django 2.2.4 on 2019-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190917_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
