# Generated by Django 2.2.4 on 2019-09-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20190918_1203'),
        ('carts', '0003_auto_20190918_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.coupon'),
            preserve_default=False,
        ),
    ]
