# Generated by Django 2.2.4 on 2019-09-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_coupon'),
    ]

    operations = [
    ]
