# Generated by Django 2.2.4 on 2019-09-29 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0023_auto_20190929_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('posta', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('order_notes', models.TextField(max_length=200)),
                ('is_Posted', models.BooleanField(default=False)),
                ('order_date', models.DateField(default=datetime.date(2019, 9, 29))),
                ('post_date', models.DateField(default=datetime.date(2019, 9, 29))),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
            ],
        ),
    ]
