# Generated by Django 2.2.4 on 2019-08-26 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('quantity_small', models.IntegerField(default=0)),
                ('quantity_medium', models.IntegerField(default=0)),
                ('quantity_large', models.IntegerField(default=0)),
                ('quantity_extralarge', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('release_time', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 1, 41, 45, 377527))),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Realtor')),
            ],
        ),
    ]
