# Generated by Django 2.2.4 on 2019-08-26 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='photos/realtors/')),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 1, 41, 45, 300424))),
            ],
        ),
    ]
