# Generated by Django 2.2.4 on 2019-09-17 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0012_auto_20190915_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 14, 1, 51, 293800)),
        ),
    ]
