# Generated by Django 2.2.4 on 2019-09-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0015_auto_20190917_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 15, 20, 47, 62802)),
        ),
    ]
