# Generated by Django 2.2.4 on 2019-09-18 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0023_auto_20190918_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 13, 9, 45, 769842)),
        ),
    ]
