# Generated by Django 2.2.4 on 2019-09-21 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0027_auto_20190920_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 9, 53, 48, 264044)),
        ),
    ]
