# Generated by Django 2.2.4 on 2019-09-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0032_auto_20190925_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 23, 52, 39, 457382)),
        ),
    ]
