# Generated by Django 2.2.4 on 2019-09-26 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0034_auto_20190926_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 21, 23, 13, 238899)),
        ),
    ]
