# Generated by Django 2.2.4 on 2019-09-26 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0035_auto_20190926_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 22, 6, 21, 422841)),
        ),
    ]
