# Generated by Django 2.2.4 on 2019-09-27 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0039_auto_20190927_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 13, 54, 32, 971335)),
        ),
    ]
