# Generated by Django 2.2.4 on 2019-09-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0042_auto_20190929_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 14, 12, 9, 46127)),
        ),
    ]
