# Generated by Django 2.2.4 on 2019-10-06 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0044_auto_20190929_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 29, 30, 342347)),
        ),
    ]
