# Generated by Django 2.2.4 on 2019-10-07 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0045_auto_20191007_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 13, 31, 12, 43202)),
        ),
    ]
