# Generated by Django 2.2.4 on 2019-10-07 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0047_auto_20191007_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 20, 1, 57, 916465)),
        ),
    ]
